# Furious Plugin Configuration

# General plugin settings
plugin:
  # If true, debug messages will be logged
  debug: false

  # If true, metrics will be collected
  metrics: true

  # If true, update checks will be performed
  update-check: true

  # Language for messages (en, fr, de, es, etc.)
  language: "en"

  # If true, colored messages will be used
  colored-messages: true

# Default configuration files
# These files will be loaded when the plugin starts
config-files:
  - "teleport.yml"
  - "guilds.yml"
  - "homes.yml"
  - "locks.yml"
  - "minigames.yml"
  - "warps.yml"
  - "wallet.yml"
