# Furious Plugin Configuration

# General plugin settings
plugin:
  # If true, debug messages will be logged
  debug: false

  # If true, metrics will be collected
  metrics: true

  # If true, update checks will be performed
  update-check: true

  # Language for messages (en, fr, de, es, etc.)
  language: "en"

  # If true, colored messages will be used
  colored-messages: true

# Rate limiting settings
# These settings control how often players can use certain commands
rate-limits:
  # Commands that are exempt from rate limiting
  exempt-commands:
    - "help"
    - "spawn"
    - "list"
    - "rules"
    - "motd"

  # Command-specific rate limits
  commands:
    # Inventory viewing commands
    invsee:
      max-uses: 5
      time-window-seconds: 60
    endersee:
      max-uses: 5
      time-window-seconds: 60

    # Teleport commands
    teleport:
      max-uses: 10
      time-window-seconds: 60

    # Guild commands
    guild:
      max-uses: 15
      time-window-seconds: 60

    # Locks commands
    locks:
      max-uses: 15
      time-window-seconds: 60

    # Minigame commands
    minigame:
      max-uses: 10
      time-window-seconds: 60

    # Homes commands
    homes:
      max-uses: 10
      time-window-seconds: 60

    # Warps commands
    warps:
      max-uses: 10
      time-window-seconds: 60

# Tombstone settings
# These settings control how tombstones work
tombstones:
  # Time in seconds before a tombstone expires (default: 30 minutes)
  timeout-seconds: 1800

  # If true, only the owner of the tombstone can access it
  owner-only-access: true

# Database settings
# These settings control how the plugin stores data
database:
  # Storage type: YAML, MYSQL, MARIADB, or SQLITE
  # YAML: Uses YAML files for storage (default)
  # MYSQL: Uses MySQL database for storage
  # MARIADB: Uses MariaDB database for storage
  # SQLITE: Uses SQLite database for storage
  storage-type: "YAML"

  # MySQL/MariaDB settings (only used if storage-type is MYSQL or MARIADB)
  mysql:
    host: "localhost"
    port: 3306
    database: "furious"
    username: "furious"
    password: "password"
    use-ssl: false

  # SQLite settings (only used if storage-type is SQLITE)
  sqlite:
    # Path to the SQLite database file (relative to plugin folder)
    file: "database.db"

  # Connection pool settings (HikariCP)
  connection-pool:
    # Maximum number of connections in the pool
    maximum-pool-size: 10
    # Minimum number of idle connections in the pool
    minimum-idle: 5
    # Maximum lifetime of a connection in the pool (in milliseconds)
    maximum-lifetime: 1800000
    # Connection timeout (in milliseconds)
    connection-timeout: 5000
    # How often to check for idle connections (in milliseconds)
    idle-timeout: 600000

# Default configuration files
# These files will be loaded when the plugin starts
config-files:
  - "teleport.yml"
  - "guilds.yml"
  - "homes.yml"
  - "locks.yml"
  - "minigames.yml"
  - "warps.yml"
  - "wallet.yml"
  - "tombstones.yml"
