name: furious
version: '1.0-SNAPSHOT'
main: com.spillhuset.furious.Furious
api-version: '1.21'
commands:
  teleport:
    description: Teleport command for requesting and managing teleports
    aliases: [tp]
    usage: /<command> [request|accept|decline|list|abort|deny|world]
  tpa:
    description: Alias for /teleport request
    usage: /<command> <player>
  tpaccept:
    description: Alias for /teleport accept
    usage: /<command> [player]
  tpdecline:
    description: Alias for /teleport decline
    usage: /<command> [player]
  invsee:
    description: View other player's inventory
    usage: /<command> <player>
  endersee:
    description: View other player's enderchest
    usage: /<command> <player>
  guild:
    description: Guild command for creating and managing guilds
    aliases: [g]
    usage: /<command> [create|invite|join|leave|info|list|kick|disband|transfer|description]
  heal:
    description: Heals yourself, or given players to maximum
    usage: /<command> [player1] ...
  feed:
    description: Feeds yourself, or given players to maximum
    usage: /<command> [player1] ...
    aliases: [food]
  locks:
    description: Manage locks for blocks
    usage: /<command> [lock|unlock|info|key]
  minigame:
    description: Manage minigames
    usage: /<command> [join|leave|list|info|create|disable|enable|start|stop|edit|spawn|save]
    aliases: [mg]
  homes:
    description: Manage your homes
    usage: /<command> [set|move|rename|delete|list|tp|buy]
    aliases: [home, h]
  warps:
    description: Manage and use warps
    usage: /<command> [create|relocate|cost|passwd|rename|delete|link|warp|list]
    aliases: [warp]
  tombstones:
    description: Manage tombstones
    usage: /<command> [purge]
  security:
    description: Manage security reviews and other security-related tasks
    usage: /<command> [status|review|help]
  bank:
    description: Manage your bank account
    usage: /<command> [balance|deposit|withdraw|transfer|claim|unclaim|info|create|rename|delete|deleteaccount|createaccount|editbalance|editinterest|help]
    aliases: [b]
  perm:
    description: Manage permissions, roles, and player permissions
    usage: /<command> [help|createrole|deleterole|listroles|roleinfo|setroledescription|addpermission|removepermission|addplayerrole|removeplayerrole|listplayerroles|addplayerpermission|removeplayerpermission|listplayerpermissions]

permissions:
  furious.invsee:
    description: Allows viewing other players' inventories
    default: op
  furious.endersee:
    description: Allows viewing other players' enderchests
    default: op
  furious.endersee.offline:
    description: Allows viewing offline players' enderchests
    default: op

  furious.teleport.*:
    description: Gives access to all teleport commands
    children:
      furious.teleport.request: true
      furious.teleport.accept: true
      furious.teleport.decline: true
      furious.teleport.list: true
      furious.teleport.abort: true
      furious.teleport.deny: true
      furious.teleport.worldconfig: true
      furious.teleport.coords: true
      furious.teleport.force: true
  furious.teleport.request:
    description: Allows requesting teleports to other players
    default: true
  furious.teleport.accept:
    description: Allows accepting teleport requests
    default: true
  furious.teleport.decline:
    description: Allows declining teleport requests
    default: true
  furious.teleport.list:
    description: Allows listing teleport requests
    default: true
  furious.teleport.abort:
    description: Allows aborting outgoing teleport requests
    default: true
  furious.teleport.deny:
    description: Allows toggling auto-deny of teleport requests
    default: true
  furious.teleport.worldconfig:
    description: Allows configuring world teleport settings
    default: op
  furious.teleport.coords:
    description: Allows using coordinate teleport commands
    default: op
  furious.teleport.force:
    description: Allows using force teleport commands
    default: op
  furious.heal.*:
    description: Gives access to all heal commands
    children:
      furious.heal.others: true
      furious.heal.self: true
  furious.heal.others:
    description: Allows healing other players
    default: op
  furious.heal.self:
    description: Allows healing yourself
    default: op
  furious.feed.*:
    description: Gives access to all feed commands
    children:
      furious.feed.others: true
      furious.feed.self: true
  furious.feed.others:
    description: Allows feeding other players
    default: op
  furious.feed.self:
    description: Allows feeding yourself
    default: op

  furious.guild.*:
    description: Gives access to all guild commands
    children:
      furious.guild.create: true
      furious.guild.invite: true
      furious.guild.join: true
      furious.guild.leave: true
      furious.guild.info: true
      furious.guild.list: true
      furious.guild.kick: true
      furious.guild.disband: true
      furious.guild.transfer: true
      furious.guild.description: true
      furious.guild.claim: true
      furious.guild.claim.unmanned: true
      furious.guild.unclaim: true
      furious.guild.unclaim.unmanned: true
      furious.guild.claims: true
      furious.guild.mobs: true
      furious.guild.homes: true
      furious.guild.homes.set: true
      furious.guild.homes.teleport: true
  furious.guild.create:
    description: Allows creating guilds
    default: true
  furious.guild.invite:
    description: Allows inviting players to guilds
    default: true
  furious.guild.join:
    description: Allows joining guilds
    default: true
  furious.guild.leave:
    description: Allows leaving guilds
    default: true
  furious.guild.info:
    description: Allows viewing guild information
    default: true
  furious.guild.list:
    description: Allows listing all guilds
    default: true
  furious.guild.kick:
    description: Allows kicking players from guilds
    default: true
  furious.guild.disband:
    description: Allows disbanding guilds
    default: true
  furious.guild.transfer:
    description: Allows transferring guild ownership
    default: true
  furious.guild.description:
    description: Allows setting guild descriptions
    default: true
  furious.guild.claim:
    description: Allows claiming chunks for a guild
    default: true
  furious.guild.claim.unmanned:
    description: Allows claiming chunks for unmanned guilds (SAFE, WAR, WILD)
    default: op
  furious.guild.unclaim:
    description: Allows unclaiming chunks from a guild
    default: true
  furious.guild.unclaim.unmanned:
    description: Allows unclaiming chunks from unmanned guilds (SAFE, WAR, WILD)
    default: op
  furious.guild.claims:
    description: Allows viewing claimed chunks of a guild
    default: true
  furious.guild.mobs:
    description: Allows controlling mob spawning in guild claimed chunks
    default: true
  furious.guild.homes:
    description: Allows managing guild homes
    default: true
  furious.guild.homes.set:
    description: Allows setting guild homes
    default: true
  furious.guild.homes.teleport:
    description: Allows teleporting to guild homes
    default: true

  furious.locks.*:
    description: Gives access to all locks commands
    children:
      furious.locks.lock: true
      furious.locks.unlock: true
      furious.locks.info: true
      furious.locks.key: true
      furious.locks.world: true
  furious.locks.lock:
    description: Allows creating lock items
    default: true
  furious.locks.unlock:
    description: Allows creating unlock items
    default: true
  furious.locks.info:
    description: Allows checking lock ownership
    default: true
  furious.locks.key:
    description: Allows creating key items
    default: true
  furious.locks.world:
    description: Allows managing locks world settings
    default: op

  furious.minigame.*:
    description: Gives access to all minigame commands
    children:
      furious.minigame.join: true
      furious.minigame.leave: true
      furious.minigame.list: true
      furious.minigame.info: true
      furious.minigame.create: true
      furious.minigame.disable: true
      furious.minigame.enable: true
      furious.minigame.start: true
      furious.minigame.stop: true
      furious.minigame.edit: true
      furious.minigame.tp: true
  furious.minigame.join:
    description: Allows joining minigame queues
    default: true
  furious.minigame.leave:
    description: Allows leaving minigame queues
    default: true
  furious.minigame.list:
    description: Allows listing available minigames
    default: true
  furious.minigame.info:
    description: Allows viewing minigame information
    default: true
  furious.minigame.create:
    description: Allows creating minigames
    default: op
  furious.minigame.disable:
    description: Allows disabling minigames
    default: op
  furious.minigame.enable:
    description: Allows enabling minigames
    default: op
  furious.minigame.start:
    description: Allows starting minigames
    default: op
  furious.minigame.stop:
    description: Allows stopping minigames
    default: op
  furious.minigame.edit:
    description: Allows editing minigames
    default: op
  furious.minigame.tp:
    description: Allows teleporting to the GameWorld
    default: op


  furious.homes.*:
    description: Gives access to all homes commands
    children:
      furious.homes.set: true
      furious.homes.move: true
      furious.homes.rename: true
      furious.homes.delete: true
      furious.homes.list: true
      furious.homes.tp: true
      furious.homes.buy: true
      furious.homes.admin: true
      furious.homes.limit.*: true
  furious.homes.set:
    description: Allows setting homes
    default: true
  furious.homes.move:
    description: Allows moving homes
    default: true
  furious.homes.rename:
    description: Allows renaming homes
    default: true
  furious.homes.delete:
    description: Allows deleting homes
    default: true
  furious.homes.list:
    description: Allows listing homes
    default: true
  furious.homes.tp:
    description: Allows teleporting to homes
    default: true
  furious.homes.buy:
    description: Allows purchasing additional home slots
    default: true
  furious.homes.admin:
    description: Allows managing other players' homes
    default: op
  furious.homes.limit.1:
    description: Sets home limit to 1
    default: false
  furious.homes.limit.2:
    description: Sets home limit to 2
    default: false
  furious.homes.limit.3:
    description: Sets home limit to 3
    default: true
  furious.homes.limit.5:
    description: Sets home limit to 5
    default: false
  furious.homes.limit.10:
    description: Sets home limit to 10
    default: false

  furious.warps.*:
    description: Gives access to all warps commands
    children:
      furious.warps.create: true
      furious.warps.relocate: true
      furious.warps.cost: true
      furious.warps.passwd: true
      furious.warps.rename: true
      furious.warps.delete: true
      furious.warps.link: true
      furious.warps.warp: true
      furious.warps.list: true
  furious.warps.create:
    description: Allows creating warps
    default: op
  furious.warps.relocate:
    description: Allows relocating warps
    default: op
  furious.warps.cost:
    description: Allows setting warp costs
    default: op
  furious.warps.passwd:
    description: Allows setting warp passwords
    default: op
  furious.warps.rename:
    description: Allows renaming warps
    default: op
  furious.warps.delete:
    description: Allows deleting warps
    default: op
  furious.warps.link:
    description: Allows linking warps to portals
    default: op
  furious.warps.warp:
    description: Allows teleporting to warps
    default: true
  furious.warps.list:
    description: Allows listing warps
    default: true

  furious.tombstones.*:
    description: Gives access to all tombstone commands
    children:
      furious.tombstones.admin: true
  furious.tombstones.admin:
    description: Allows managing tombstones (purge, etc.)
    default: op

  furious.security.*:
    description: Gives access to all security commands
    children:
      furious.security.admin: true
  furious.security.admin:
    description: Allows managing security reviews and other security-related tasks
    default: op

  furious.bank.*:
    description: Gives access to all bank commands
    children:
      furious.bank.balance: true
      furious.bank.deposit: true
      furious.bank.withdraw: true
      furious.bank.transfer: true
      furious.bank.claim: true
      furious.bank.unclaim: true
      furious.bank.info: true
      furious.bank.create: true
      furious.bank.rename: true
      furious.bank.delete: true
      furious.bank.deleteaccount: true
      furious.bank.createaccount: true
      furious.bank.editbalance: true
      furious.bank.editinterest: true
      furious.bank.admin: true
  furious.bank.balance:
    description: Allows checking bank balance
    default: true
  furious.bank.deposit:
    description: Allows depositing to bank
    default: true
  furious.bank.withdraw:
    description: Allows withdrawing from bank
    default: true
  furious.bank.transfer:
    description: Allows transferring funds between bank accounts
    default: true
  furious.bank.claim:
    description: Allows claiming chunks for banks
    default: op
  furious.bank.unclaim:
    description: Allows unclaiming chunks from banks
    default: op
  furious.bank.info:
    description: Allows viewing bank information at current location
    default: true
  furious.bank.create:
    description: Allows creating banks
    default: op
  furious.bank.rename:
    description: Allows renaming banks
    default: op
  furious.bank.delete:
    description: Allows deleting banks
    default: op
  furious.bank.deleteaccount:
    description: Allows deleting accounts from banks
    default: op
  furious.bank.createaccount:
    description: Allows creating accounts in banks
    default: op
  furious.bank.editbalance:
    description: Allows editing player balances in banks
    default: op
  furious.bank.editinterest:
    description: Allows editing bank interest rates
    default: op
  furious.bank.admin:
    description: Allows administrative bank operations
    default: op
  furious.permission.*:
    description: Gives access to all permission management commands
    children:
      furious.permission.createrole: true
      furious.permission.deleterole: true
      furious.permission.listroles: true
      furious.permission.roleinfo: true
      furious.permission.setroledescription: true
      furious.permission.addpermission: true
      furious.permission.removepermission: true
      furious.permission.addplayerrole: true
      furious.permission.removeplayerrole: true
      furious.permission.listplayerroles: true
      furious.permission.addplayerpermission: true
      furious.permission.removeplayerpermission: true
      furious.permission.listplayerpermissions: true
  furious.permission.createrole:
    description: Allows creating roles
    default: op
  furious.permission.deleterole:
    description: Allows deleting roles
    default: op
  furious.permission.listroles:
    description: Allows listing all roles
    default: op
  furious.permission.roleinfo:
    description: Allows viewing detailed information about a role
    default: op
  furious.permission.setroledescription:
    description: Allows setting the description of a role
    default: op
  furious.permission.addpermission:
    description: Allows adding a permission to a role
    default: op
  furious.permission.removepermission:
    description: Allows removing a permission from a role
    default: op
  furious.permission.addplayerrole:
    description: Allows adding a role to a player
    default: op
  furious.permission.removeplayerrole:
    description: Allows removing a role from a player
    default: op
  furious.permission.listplayerroles:
    description: Allows listing the roles assigned to a player
    default: op
  furious.permission.addplayerpermission:
    description: Allows adding a direct permission to a player
    default: op
  furious.permission.removeplayerpermission:
    description: Allows removing a direct permission from a player
    default: op
  furious.permission.listplayerpermissions:
    description: Allows listing the direct permissions assigned to a player
    default: op
  furious.*:
    description: Gives access to all furious plugin permissions
    children:
      furious.invsee: true
      furious.endersee: true
      furious.endersee.offline: true
      furious.teleport.*: true
      furious.heal.*: true
      furious.feed.*: true
      furious.guild.*: true
      furious.locks.*: true
      furious.minigame.*: true
      furious.homes.*: true
      furious.warps.*: true
      furious.tombstones.*: true
      furious.security.*: true
      furious.bank.*: true
      furious.permission.*: true
      furious.ratelimit.exempt: true
  furious.ratelimit.exempt:
    description: Exempts a player from all rate limits
    default: op
