name: Furious
version: '1.0-SNAPSHOT'
main: com.spillhuset.furious.Furious
api-version: '1.21'

commands:
  wallet:
    description: Wallet command
  homes:
    description: Homes command
  guild:
    description: Guild command
  warps:
    description: Warps command
  banks:
    description: Banks command
  shops:
    description: Shops command
  teleport:
    description: Teleport command
    aliases: [tp, tpa, tpaccept, tpdecline, tpdeny, tppos, tpall]
  tombstones:
    description: Tombstones administration command
  locks:
    description: Locks command
  checklist:
    description: Checklist command
  auctions:
    description: Auctions command
  invsee:
    description: View and edit a player's inventory (op only)
  endersee:
    description: View and edit a player's ender chest (op only)
  heal:
    description: Heal yourself or other players
  feed:
    description: Feed yourself or other players
  repair:
    description: Repair items (hand or all). Optionally target a player
  worldspawn:
    description: Teleport to the current world's spawn (ops only)
  setworldspawn:
    description: Set the current world's spawn to your location (ops only)
  world:
    description: World utilities (setspawn, spawn, info)
  profession:
    description: View and set your professions
  ban:
    description: Ban a player (temporary or permanent)
  unban:
    description: Unban a player

permissions:
  furious.auctions:
    default: true
  furious.auctions.claim:
    default: op
  furious.auctions.unclaim:
    default: op
  furious.auctions.open:
    default: op
  furious.auctions.spawn:
    default: op
  furious.auctions.teleport:
    default: op

  furious.repair:
    default: op
  furious.repair.self:
    default: true
  furious.repair.all:
    default: op
  furious.repair.others:
    default: op

  furious.locks:
    default: true
  furious.locks.worlds:
    default: op
  furious.homes:
    default: true
  furious.homes.others:
    default: op
  furious.homes.set:
    default: true
  furious.homes.remove:
    default: true
  furious.homes.teleport:
    default: true
  furious.homes.list:
    default: true
  furious.homes.move:
    default: true
  furious.homes.rename:
    default: true
  furious.homes.buy:
    default: true
  furious.homes.migrate:
    default: op
  furious.homes.worlds:
    default: op
  furious.homes.set.others:
    default: op
  furious.homes.remove.others:
    default: op
  furious.homes.teleport.others:
    default: op
  furious.homes.list.others:
    default: op
  furious.homes.move.others:
    default: op
  furious.homes.rename.others:
    default: op
  furious.homes.buy.others:
    default: op
  furious.homes.admin:
    default: op
    children:
      furious.homes.*: true
  furious.homes.users:
    default: true
    children:
      furious.homes: true
      furious.homes.set: true
      furious.homes.remove: true
      furious.homes.teleport: true
      furious.homes.list: true
      furious.homes.move: true
      furious.homes.rename: true
      furious.homes.buy: true

  furious.wallet:
    description: Access to Wallet command
    default: true
  furious.wallet.balance:
    default: true
  furious.wallet.balance.others:
    default: op
  furious.wallet.pay:
    default: true
  furious.wallet.set:
    default: op
  furious.wallet.add:
    default: op
  furious.wallet.subtract:
    default: op
  furious.wallet.reload:
    default: op
  furious.wallet.log:
    default: op
  furious.wallet.admin:
    default: op
    children:
      furious.wallet.*: true
  furious.wallet.users:
    default: true
    children:
      furious.wallet: true
      furious.wallet.balance: true
      furious.wallet.pay: true

  furious.guild:
    default: true
  furious.guild.create:
    default: true
  furious.guild.create.admin:
    default: op
  furious.guild.rename:
    default: true
  furious.guild.rename.others:
    default: op

  furious.tombstones:
    default: op
  furious.tombstones.clear:
    default: op
  furious.guild.delete:
    default: true
  furious.guild.delete.others:
    default: op
  furious.guild.invite:
    default: true
  furious.guild.accept:
    default: true
  furious.guild.decline:
    default: true
  furious.guild.kick:
    default: true
  furious.guild.kick.others:
    default: op
  furious.guild.promote:
    default: true
  furious.guild.promote.others:
    default: op
  furious.guild.demote:
    default: true
  furious.guild.demote.others:
    default: op
  furious.guild.claim:
    default: true
  furious.guild.claims:
    default: op
  furious.guild.unclaim:
    default: true
  furious.guild.unclaims:
    default: op
  furious.guild.setopen:
    default: true
  furious.guild.setopen.others:
    default: op
  furious.guild.join:
    default: true
  furious.guild.worlds:
    default: op
  furious.guild.list:
    default: true
  furious.guild.info:
    default: true

  furious.warps:
    default: true
  furious.warps.set:
    default: op
  furious.warps.move:
    default: op
  furious.warps.rename:
    default: op
  furious.warps.setcost:
    default: op
  furious.warps.setpassword:
    default: op
  furious.warps.remove:
    default: op
  furious.warps.connectportal:
    default: op
  furious.warps.portalclaim:
    default: op
  furious.warps.portalclear:
    default: op
  furious.warps.teleport:
    default: true
  furious.warps.list:
    default: true

  furious.banks:
    default: true
  furious.banks.create:
    default: op
  furious.banks.rename:
    default: op
  furious.banks.delete:
    default: op
  furious.banks.claim:
    default: op
  furious.banks.unclaim:
    default: op
  furious.banks.setinterest:
    default: op
  furious.banks.type:
    default: op
  furious.banks.createaccount:
    default: true
  furious.banks.deposit:
    default: true
  furious.banks.withdraw:
    default: true
  furious.banks.deleteaccount:
    default: true
  furious.banks.list:
    default: true
  furious.banks.open:
    default: op
  furious.banks.spawn:
    default: op
  furious.banks.teleport:
    default: op
  furious.banks.teleport.others:
    default: op
  furious.banks.balances:
    default: true
  furious.banks.balances.others:
    default: op
  furious.banks.summary:
    default: true
  furious.banks.summary.others:
    default: op
  furious.banks.audit:
    default: op
  furious.banks.exportdb:
    default: op
  furious.banks.migrate:
    default: op

  furious.shops:
    default: true
  furious.shops.claim:
    default: op
  furious.shops.unclaim:
    default: op
  furious.shops.setbuyprice:
    default: op
  furious.shops.setsellprice:
    default: op
  furious.shops.create:
    default: op
  furious.shops.delete:
    default: op
  furious.shops.spawn:
    default: op
  furious.shops.teleport:
    default: op
  furious.shops.list:
    default: true
  furious.shops.additem:
    default: op
  furious.shops.removeitem:
    default: op
  furious.shops.listitem:
    default: true
  furious.shops.buy:
    default: true
  furious.shops.sell:
    default: true
  furious.shops.stock:
    default: op
  furious.shops.restock:
    default: op
  furious.shops.type:
    default: op
  furious.shops.open:
    default: op

  furious.teleport:
    default: true
  furious.teleport.request:
    default: true
  furious.teleport.accept:
    default: true
  furious.teleport.decline:
    default: true
  furious.teleport.cancel:
    default: true
  furious.teleport.deny:
    default: true

  furious.teleport.position:
    default: op
  furious.teleport.all:
    default: op
  furious.teleport.teleport:
    default: op

  furious.checklist:
    default: true
  furious.checklist.biomes:
    default: true
  furious.checklist.biomes.others:
    default: op
  furious.checklist.monsters:
    default: true
  furious.checklist.monsters.others:
    default: op
  furious.checklist.taming:
    default: true
  furious.checklist.taming.others:
    default: op

  furious.invsee:
    default: op
  furious.endersee:
    default: op

  furious.heal:
    default: op
  furious.heal.others:
    default: op

  furious.feed:
    default: op
  furious.feed.others:
    default: op

  furious.worldspawn:
    default: true
  furious.worldspawn.teleport:
    default: op
  furious.worldspawn.teleport.others:
    default: op
  furious.worldspawn.set:
    default: op

  furious.world:
    default: true
  furious.world.setspawn:
    default: op
  furious.world.spawn:
    default: op
  furious.world.spawn.others:
    default: op
  furious.world.info:
    default: op

  furious.profession:
    default: true
  furious.profession.others:
    default: op

  furious.profession.veinminer:
    description: Allows mining entire connected ore veins when breaking an ore with a pickaxe
    default: op
  furious.profession.treechopper:
    description: Allows chopping entire connected trees (logs) when breaking a log with an axe
    default: op

  furious.ban:
    default: op
  furious.unban:
    default: op