name: Furious
version: '1.0-SNAPSHOT'
main: com.spillhuset.furious.Furious
api-version: '1.21'

commands:
  wallet:
    description: Wallet command
  homes:
    description: Homes command
  guild:
    description: Guild command
  warps:
    description: Warps command
  banks:
    description: Banks command
  shops:
    description: Shops command
  teleport:
    description: Teleport request command
  tombstones:
    description: Tombstones administration command
  locks:
    description: Locks command
  checklist:
    description: Checklist command

permissions:
  furious.locks:
    default: true
  furious.locks.worlds:
    default: op
  furious.homes:
    default: true
  furious.homes.others:
    default: op
  furious.homes.set:
    default: true
  furious.homes.remove:
    default: true
  furious.homes.teleport:
    default: true
  furious.homes.list:
    default: true
  furious.homes.move:
    default: true
  furious.homes.rename:
    default: true
  furious.homes.buy:
    default: true
  furious.homes.worlds:
    default: op
  furious.homes.set.others:
    default: op
  furious.homes.remove.others:
    default: op
  furious.homes.teleport.others:
    default: op
  furious.homes.list.others:
    default: op
  furious.homes.move.others:
    default: op
  furious.homes.rename.others:
    default: op
  furious.homes.buy.others:
    default: op
  furious.homes.admin:
    default: op
    children:
      furious.homes.*: true
  furious.homes.users:
    default: true
    children:
      furious.homes: true
      furious.homes.set: true
      furious.homes.remove: true
      furious.homes.teleport: true
      furious.homes.list: true
      furious.homes.move: true
      furious.homes.rename: true
      furious.homes.buy: true

  furious.wallet:
    description: Access to Wallet command
    default: true
  furious.wallet.balance:
    default: true
  furious.wallet.balance.others:
    default: op
  furious.wallet.pay:
    default: true
  furious.wallet.set:
    default: op
  furious.wallet.add:
    default: op
  furious.wallet.subtract:
    default: op
  furious.wallet.reload:
    default: op
  furious.wallet.log:
    default: op
  furious.wallet.admin:
    default: op
    children:
      furious.wallet.*: true
  furious.wallet.users:
    default: true
    children:
      furious.wallet: true
      furious.wallet.balance: true
      furious.wallet.pay: true

  furious.guild:
    default: true
  furious.guild.create:
    default: true
  furious.guild.create.admin:
    default: op
  furious.guild.rename:
    default: true
  furious.guild.rename.others:
    default: op

  furious.tombstones:
    default: op
  furious.tombstones.clear:
    default: op
  furious.guild.delete:
    default: true
  furious.guild.delete.others:
    default: op
  furious.guild.invite:
    default: true
  furious.guild.accept:
    default: true
  furious.guild.decline:
    default: true
  furious.guild.kick:
    default: true
  furious.guild.kick.others:
    default: op
  furious.guild.promote:
    default: true
  furious.guild.promote.others:
    default: op
  furious.guild.demote:
    default: true
  furious.guild.demote.others:
    default: op
  furious.guild.claim:
    default: true
  furious.guild.claims:
    default: op
  furious.guild.unclaim:
    default: true
  furious.guild.unclaims:
    default: op
  furious.guild.setopen:
    default: true
  furious.guild.setopen.others:
    default: op
  furious.guild.join:
    default: true
  furious.guild.worlds:
    default: op
  furious.guild.list:
    default: true

  furious.warps:
    default: true
  furious.warps.set:
    default: op
  furious.warps.move:
    default: op
  furious.warps.rename:
    default: op
  furious.warps.setcost:
    default: op
  furious.warps.setpassword:
    default: op
  furious.warps.remove:
    default: op
  furious.warps.connectportal:
    default: op
  furious.warps.teleport:
    default: true
  furious.warps.list:
    default: true

  furious.banks:
    default: true
  furious.banks.create:
    default: op
  furious.banks.rename:
    default: op
  furious.banks.delete:
    default: op
  furious.banks.claim:
    default: op
  furious.banks.unclaim:
    default: op
  furious.banks.setinterest:
    default: op
  furious.banks.type:
    default: op
  furious.banks.createaccount:
    default: true
  furious.banks.deposit:
    default: true
  furious.banks.withdraw:
    default: true
  furious.banks.deleteaccount:
    default: true
  furious.banks.list:
    default: true

  furious.shops:
    default: true
  furious.shops.claim:
    default: op
  furious.shops.unclaim:
    default: op
  furious.shops.setbuyprice:
    default: op
  furious.shops.setsellprice:
    default: op
  furious.shops.create:
    default: op
  furious.shops.delete:
    default: op
  furious.shops.spawn:
    default: op
  furious.shops.teleport:
    default: op
  furious.shops.list:
    default: true
  furious.shops.additem:
    default: op
  furious.shops.removeitem:
    default: op
  furious.shops.listitem:
    default: true
  furious.shops.buy:
    default: true
  furious.shops.sell:
    default: true
  furious.shops.stock:
    default: op
  furious.shops.restock:
    default: op
  furious.shops.type:
    default: op

  furious.teleport:
    default: true
  furious.teleport.request:
    default: true
  furious.teleport.accept:
    default: true
  furious.teleport.decline:
    default: true
  furious.teleport.cancel:
    default: true
  furious.teleport.deny:
    default: true

  furious.checklist:
    default: true
  furious.checklist.biomes:
    default: true
  furious.checklist.biomes.others:
    default: op
  furious.checklist.monsters:
    default: true
  furious.checklist.monsters.others:
    default: op
  furious.checklist.taming:
    default: true
  furious.checklist.taming.others:
    default: op